config/routes.rb
Rails.application.routes.draw do
  get 'user/spotify'

  root 'search#index'

  get '/artists', to: 'artists#index'
  get '/artists/playlist', to: 'artists#show', as: 'artist'

  get '/auth/spotify/callback', to: 'users#spotify'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  include ArtistsHelper
  def index
    if !params[:artist1_name].empty? && !params[:artist2_name].empty?
      @artist1list = RSpotify::Artist.search(params[:artist1_name])
      @artist2list = RSpotify::Artist.search(params[:artist2_name])
    else
      redirect_to root_path
    end
  end

  def show
    @allTracks = []
    $collabTrackList = []
    $artist1 = RSpotify::Artist.find(params[:artist1_id])
    $artist2 = RSpotify::Artist.find(params[:artist2_id])
    $artist1.albums(country: 'US').each do |album|
      album.tracks.each do |track|
        @allTracks << track
      end
    end
    $artist2.albums(country: 'US').each do |album|
      album.tracks.each do |track|
        @allTracks << track
      end
    end
    @allTracks.each do |track|
      track_artists = track.artists
      containsArtist1 = false
      containsArtist2 = false
      track_artists.each do |artist|
        containsArtist1 ||= artist.id.eql?(params[:artist1_id])
        containsArtist2 ||= artist.id.eql?(params[:artist2_id])
      end
      if containsArtist1 && containsArtist2 && !tracklistContains($collabTrackList,
                                                                  track.name)
        $collabTrackList << track
      end
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def spotify
    $spotify_user = RSpotify::User.new(request.env['omniauth.auth'])
    $new_playlist = $spotify_user.create_playlist!($artist1.name + " x " + $artist2.name)
    $new_playlist.add_tracks!($collabTrackList)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper

  def tracklistContains(tracklist, title)
    tracklist.each do |track|
      if track.name.eql?(title)
        return true
      end
    end
    false
  end

end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/artists/index.html.erb
<div class="container-fluid">
  <div class="page-header">
    <h1>Select the correct artists</h1>
  </div>
  <%= form_tag artist_path, method: "get", html: {class: "form"} do %>
      <div class="form-group col-xs-6">
        <label class="control-label">Artists matching <b><%= params[:artist1_name].titlecase %></b></label>
        <%= select_tag("artist1_id",
                       options_from_collection_for_select(@artist1list, :id, :name), class: "form-control ") %>
      </div>
      <div class="form-group col-xs-6">
        <label class="control-label">Artists matching <b><%= params[:artist2_name].titlecase %></b></label>
        <%= select_tag("artist2_id",
                       options_from_collection_for_select(@artist2list, :id, :name), class: "form-control") %>
      </div>
      <%= submit_tag "Submit", class: "btn btn-primary center-block" %>
  <% end %>
</div>

app/views/artists/show.html.erb
<div class="container-fluid">
  <div class="page-header">
    <h1><%= "#{$artist1.name.titlecase} and #{$artist2.name.titlecase} tracks" %></h1>
    <p><%= "#{$artist1.name.titlecase} and #{$artist2.name.titlecase} have collaborated on #{$collabTrackList.size} tracks" %></p>
  </div>
  <% $collabTrackList.each do |track| %>
      <div class="row">
        <div class="col-xs-3"><%= track.name %> </div>
        <div class="col-xs-3"><%= track.album.name %> </div>
        <div class="col-xs-3">
          <%= track.artists.map{|a| a.name}.join(", ") %>
        </div>
        <div class="col-xs-3"><img src="<%= track.album.images[0]['url']%>" width="150" height="150"/></div>
      </div>
  <% end %>


  <footer>
    <ul class="nav nav-pills">
      <li role="presentation" class="active"><a href="/">Start Over</a></li>
      <% if $collabTrackList.size > 0 %>
          <li role="presentation" class="active"><a href="/auth/spotify">Make it a playlist!</a></li>
      <% end %>
    </ul>

  </footer>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Collab</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application.js', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <ul class="nav nav-pills">
    <li role="presentation" class="active"><a href="/">Collab</a></li>
  </ul>
  <%= yield %>
</body>
</html>

app/views/search/index.html.erb
<div class="container-fluid">
  <h1 class="page-header">Collab</h1>
  <%= form_tag artists_path, method: "get", html: {class: "form"} do %>
      <div class="form-group col-xs-4">
        <%= text_field_tag(:artist1_name, "", placeholder: "Enter first artist's name", class: "form-control",
                           autocomplete: "off") %>
      </div>
      <div class="form-group col-xs-4">
        <%= text_field_tag(:artist2_name, "", placeholder: "Enter second artist's name", class: "form-control",
                           autocomplete: "off") %>
      </div>
      <%= submit_tag "Search", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/users/spotify.html.erb
<div class="container-fluid">
  <h1 class="page-header">Your New Playist</h1>
  <% url = $new_playlist.external_urls['spotify'].split('/') %>
  <iframe src=<%="https://open.spotify.com/embed?uri=spotify:user:#{url[4]}:playlist:#{url[6]}"%>
              width="300" height="380" frameborder="0" allowtransparency="true"></iframe>
</div>